### ISSUE TITLE
upgrading pagespeed to 1.10.33.7 

### ISSUE THREAD

**Issue by mbunzel** [istenrot/centos-nginx-http2#2]
ngx_pagespeed was recently updated to v1.10.33.7, which contains an important security fix. 

I've looked into creating a pull request but generate-spec.yml produces a spec file that is different than the current one (it's missing %package module-pagespeed and other stuff) and breaks the build due to additional spaces after the newline separator in 4 different places. 

If you've given up on the generate-spec.yml approach and just edit the spec file manually let me know and I'll send a pull request with manual changes to variables.yml and nginx.spec.

**Comment by istenrot** [comment]
Currently building with ngx_pagespeed 1.11.33.4.

The build scripts have been completely overhauled and generate-spec.yml doesn't exists anymore.
